#   Description: This workflow is used to build and publish a Docker image into Gitea Container Registry.
#                The image is tagged with the release tag and latest.
#                If the release is a pre-release, the image is named <repo-name>-pre, otherwise it just uses the repo name.
#   Needed Secrets: PORTAINER_WEBHOOK
#   Needed Variables: None
#   Important parameter: Path to the Dockerfile folder (context), Name of the solution, project and name of the DbContext (restore and add-migration)

name: Build and publish Docker image into Gitea Container Registry

on:
  release:
    types: [published]
  push:
    branches:
      - dev

permissions:
  contents: write
  packages: write

jobs:
  # -------------------------------------------
  # 1) AUTO-GENERATE & COMMIT EF MIGRATIONS
  # -------------------------------------------
  auto-generate-migration:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup .NET (with cache)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore solution
        run: dotnet restore BackendAuthTemplate.sln # Solution name

      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Check for pending EF model changes
        id: ef_check
        run: |
          set +e
          # Path to the project with the DbContext
          # Path to the startup project
          # Name of your DbContext
          dotnet ef migrations has-pending-model-changes \
            --project ./src/Infrastructure \
            --startup-project ./src/API \
            --context AppDbContext
          rc=$?
          set -e
          if [ "$rc" -eq 0 ]; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
          exit 0

      - name: Add EF migration (only if model changes detected)
        id: add_migration
        if: steps.ef_check.outputs.has_changes == 'true'
        run: |
          set -e
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          # Path to the project with the DbContext
          # Path to the startup project
          # Name of your DbContext
          dotnet ef migrations add Auto_${TIMESTAMP} \
            --project ./src/Infrastructure \
            --startup-project ./src/API \
            --context AppDbContext \
            -o Data/Migrations || true
          echo "TIMESTAMP=${TIMESTAMP}" >> $GITHUB_OUTPUT

      - name: Check for changes and commit if any
        id: maybe_commit
        if: steps.ef_check.outputs.has_changes == 'true'
        run: |
          set -e
          git --no-pager status --porcelain || true
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add -A
            git commit -m "Auto migration for ${GITHUB_SHA} [skip ci]" || true
            git push origin dev
            echo "committed=true" >> $GITHUB_OUTPUT
          else
            echo "committed=false" >> $GITHUB_OUTPUT
          fi

  # -------------------------------------------
  # 2) BUILD AND PUBLISH IMAGE
  # -------------------------------------------
  build-and-publish-image:
    runs-on: ubuntu-latest
    needs: [auto-generate-migration]
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: If we just created a migration, pull the latest dev commit
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        run: |
          git checkout dev
          git pull --ff-only origin dev || true

      - id: lower-repo
        name: Lowercase repo
        run: |
          repo="${GITHUB_REPOSITORY,,}"
          echo "repository=$repo" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: pre-image-tag
        name: adds -pre to the image tag if it is a pre-release
        if: github.event_name == 'release' && github.event.release.prerelease == true
        run: echo "pre=-pre" >> $GITHUB_OUTPUT

      - name: Build and push release image
        if: github.event_name == 'release'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/API/Dockerfile # Path to the Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.lower-repo.outputs.repository }}${{ steps.pre-image-tag.outputs.pre }}:latest
            ghcr.io/${{ steps.lower-repo.outputs.repository }}${{ steps.pre-image-tag.outputs.pre }}:${{ github.event.release.tag_name }}

      - name: Build and push dev image
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/API/Dockerfile # Path to the Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.lower-repo.outputs.repository }}:dev

      - name: Trigger Portainer webhook
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        uses: sozo-design/curl@v1.0.2
        with:
          args: -X POST ${{ secrets.PORTAINER_WEBHOOK }}